class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
  # Routes for reconciliations generated by controller generator
  # (Moved to nested routes under contracts)
  # End routes for reconciliations

  # Routes for comments generated by controller generator
  resources :comments, only: [:create]
  # End routes for comments

  # Routes for contracts generated by controller generator
  resources :contracts
  # End routes for contracts

  # Authentication routes
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout

  # Lawyer backend routes
  scope :lawyer, as: :lawyer do
    resources :companies, controller: 'lawyer/companies' do
      member do
        get :enter
        post :suspend
        post :resume
      end
    end
    resources :lawyer_accounts, controller: 'lawyer/lawyer_accounts', except: [:show]
    resources :company_accounts, controller: 'lawyer/company_accounts', only: [:index, :create, :update, :destroy]
  end

  # Boss dashboard routes
  namespace :boss do
    root 'dashboard#index'
    get 'dashboard', to: 'dashboard#index'
  end

  # 企业工作台路由
  get 'workbench', to: 'workbench#index', as: :workbench_index

  # Contract management
  resources :contracts do
    resources :reconciliations, only: [:create, :destroy]
    resources :comments, only: [:create], defaults: { commentable_type: 'Contract' }
  end

  # Case management (Lawyer only)
  resources :cases do
    resources :work_logs, only: [:create, :destroy]
    resources :comments, only: [:create], defaults: { commentable_type: 'Case' }
    member do
      post :request_deletion    # Employee request deletion
      post :confirm_deletion    # Boss confirm deletion
      post :delete_directly     # Boss direct deletion
      get :download_archive     # Boss download archived case files
    end
  end

  # Major issues discussion (All users can create)
  resources :major_issues do
    resources :comments, only: [:create], defaults: { commentable_type: 'MajorIssue' }
    member do
      post :request_deletion
      post :confirm_deletion
      post :delete_directly
    end
  end

  # Pending tasks
  resources :todos, only: [:index] do
    member do
      post :mark_done
    end
  end

  # write your business logic routes here

  # API routes
  namespace :api do
    namespace :v1 do
      get 'health', to: 'health#index'
    end
  end

  root 'home#index'

  # Do not write business logic at admin dashboard
  namespace :admin do
    resources :admin_oplogs, only: [:index, :show]
    resources :administrators
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    # Mount GoodJob dashboard
    mount GoodJob::Engine => 'good_job', :constraints => AdminConstraint.new

    root to: 'dashboard#index'
  end

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage')
    }
end
