Rails.application.routes.draw do
  # Routes for lawyer_fee_analytics generated by controller generator
  resources :lawyer_fee_analytics do
    get :dashboard, on: :collection
    get :export_detailed, on: :collection
    get :export_lawyer_summary, on: :collection
    get :export_company_summary, on: :collection
  end
  # End routes for lawyer_fee_analytics

  # Routes for contract_risks generated by controller generator
  resources :contract_risks do
    get :dashboard, on: :collection
  end
  # End routes for contract_risks

  # Root path - redirect based on user type
  root "home#index"

  # Lawyer namespace routes
  namespace :lawyer do
    resources :companies do
      member do
        post :enter
        post :suspend
        post :resume
      end
      collection do
        get :announcements
      end
    end
    resources :company_accounts
    resource :profile, only: [:edit, :update]
    resources :announcements, only: [:index] do
      collection do
        post :enter, as: :enter
        post :dismiss
      end
    end
  end

  resources :major_issue_analytics do
    get :dashboard, on: :collection
  end
  
  resources :case_analytics, only: [] do
    collection do
      get :dashboard
      get :export_report
    end
  end
  
  resources :contract_analytics, only: [] do
    collection do
      get :dashboard
      get :export_report
    end
  end

  # Main resources
  resources :contracts do
    collection do
      get :calendar
    end
    member do
      post :mark_as_reviewed
      get :export_archive
      post :renew
      get :renewal_settings
      post :append_evidence_files
      get :new_case_from_contract
    end
    resources :reconciliations, only: [:create, :destroy] do
      member do
        post :mark_as_reviewed
      end
      collection do
        post :quick_create_current_month
      end
      resources :comments, only: [:create], controller: "comments"
    end
    resources :comments, only: [:create], controller: "comments"
  end
  resources :cases do
    resources :case_team_members, only: [:create, :destroy]
    resources :case_team_collaborations, only: [:create, :destroy]
    resources :work_logs, only: [:index, :create, :update, :destroy] do
      member do
        post :append_attachments
      end
    end
    resources :comments, only: [:create, :update, :destroy], controller: "comments"
    collection do
      get :calendar
      get :my_cases
      get :my_lead_cases
      get :team_workload
    end
    member do
      post :request_deletion
      post :confirm_deletion
      delete :delete_directly
      get :download_archive
      get :export_all_materials
      post :append_attachments
      patch :update_property_preservation
      patch :update_lawyer_fee
      post :add_relation
      delete :remove_relation
    end
  end
  
  resources :case_filters, only: [:create, :update, :destroy] do
    member do
      post :set_as_default
    end
  end
  resources :major_issues do
    resources :comments, only: [:create, :update, :destroy], controller: "comments"
    member do
      post :mark_as_read
      post :follow
      post :unfollow
      post :conclude
      post :reopen
      patch :update_conclusion
      post :mark_as_reviewed
      post :resolve
      post :archive
      get :export_archive
      post :create_todo_item
      patch :complete_todo_item
      delete :delete_todo_item
    end
  end
  resources :reconciliations, only: [] do
    resources :comments, only: [:create], controller: "comments"
  end
  resources :comments, only: [:update, :destroy] do
    member do
      post :pin
      post :unpin
      post :mark_as_key_opinion
      post :unmark_as_key_opinion
      post :append_attachments
    end
  end
  resources :saved_filters, only: [:create, :update, :destroy]
  resources :todos, only: [:index] do
    member do
      patch :toggle
    end
  end
  resources :announcements, only: [:index] do
    member do
      post :mark_as_read
      post :dismiss
    end
    collection do
      post :enter
      post :dismiss, as: :dismiss_collection
    end
  end

  # Search
  get "search", to: "searches#index"

  # Secure blob access - all file downloads must go through permission check
  get "/secure/blobs/:signed_id/*filename", to: "secure_blobs#show", as: :secure_blob, defaults: { disposition: "inline" }
  get "/secure/blobs/:signed_id/*filename/download", to: "secure_blobs#show", as: :secure_blob_download, defaults: { disposition: "attachment" }

  # Attachments - for managing uploaded files
  delete "attachments/:id", to: "attachments#destroy", as: :attachment

  # Workbench (old enterprise user interface, keeping for backward compatibility)
  resources :workbench, only: [:index]

  # Profile management
  resource :profile, only: [:edit, :update]

  # Authentication routes
  resource :session, only: [:new, :create, :destroy]
  get  "login",          to: "sessions#new",            as: :login
  post "login",          to: "sessions#create"
  delete "logout",       to: "sessions#destroy",         as: :logout
  get  "select_company", to: "sessions#select_company",  as: :select_company
  post "enter_company",  to: "sessions#enter_company",   as: :enter_company

  # Account unlock
  get "unlock_account/:token", to: "account_unlocks#show", as: :unlock_account

  # Health check for deployment monitoring
  get "up", to: "rails/health#show", as: :rails_health_check
  
  # Custom health check endpoints
  get "health", to: "health#index"
  get "health/detailed", to: "health#detailed"

  # Demo routes (development/testing)
  if Rails.env.development?
    get "design_demo", to: "sessions#design_demo"
    get "navbar_color_schemes", to: "home#navbar_color_schemes_demo"
  end

  # GoodJob Web UI
  mount GoodJob::Engine => "/admin/good_job", as: :admin_good_job

  # Admin namespace
  namespace :admin do
    root "dashboard#index"
    resources :dashboard, only: [:index]

    # 企业管理（核心）
    resources :companies do
      member do
        post :suspend
        post :resume
        post :archive
      end
      # 企业成员管理
      resources :company_memberships, only: [:new, :create, :destroy]
    end

    # 律师账号管理
    resources :lawyer_accounts do
      member do
        post :toggle_status
      end
    end

    # 企业用户管理（跨企业账号）
    resources :company_users do
      member do
        post :toggle_status
      end
    end

    # 其他
    resources :contract_tags
    resources :announcements
    resources :administrators
    resources :admin_oplogs, only: [:index, :show]
    resource :account, only: [:edit, :update]
    resource :session, only: [:new, :create, :destroy]
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy", as: :logout
  end
end
