class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
  # Routes for reconciliations generated by controller generator
  # (Moved to nested routes under contracts)
  # End routes for reconciliations

  # Routes for comments generated by controller generator
  resources :comments, only: [:create]
  # End routes for comments

  # Routes for regulations generated by controller generator
  resources :regulations
  # End routes for regulations

  # Routes for contracts generated by controller generator
  resources :contracts
  # End routes for contracts

  # Routes for employees generated by controller generator
  resources :employees
  # End routes for employees

  # Authentication routes
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout

  # Lawyer backend routes
  scope :lawyer, as: :lawyer do
    resources :companies, controller: 'lawyer/companies' do
      member do
        get :enter
      end
    end
    resources :lawyer_accounts, controller: 'lawyer/lawyer_accounts', except: [:show]
    resources :company_accounts, controller: 'lawyer/company_accounts', only: [:index, :create, :update, :destroy]
  end

  # Boss dashboard routes
  namespace :boss do
    root 'dashboard#index'
    get 'dashboard', to: 'dashboard#index'
  end

  # Employee management (HR role)
  resources :employees do
    member do
      get :export_pdf
    end
    resources :comments, only: [:create], defaults: { commentable_type: 'Employee' }
  end

  # Contract management (Contract role)
  resources :contracts do
    resources :reconciliations, only: [:create, :destroy]
    resources :comments, only: [:create], defaults: { commentable_type: 'Contract' }
  end

  # Regulation management (HR role)
  resources :regulations do
    resources :comments, only: [:create], defaults: { commentable_type: 'Regulation' }
  end

  # write your business logic routes here

  # API routes
  namespace :api do
    namespace :v1 do
      get 'health', to: 'health#index'
    end
  end

  root 'home#index'

  # Do not write business logic at admin dashboard
  namespace :admin do
    resources :admin_oplogs, only: [:index, :show]
    resources :administrators
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    # Mount GoodJob dashboard
    mount GoodJob::Engine => 'good_job', :constraints => AdminConstraint.new

    root to: 'dashboard#index'
  end

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage')
    }
end
